### ISSUE TITLE
Request to change the warning message "Wait... What... Dude, you are already loading items..."

### ISSUE THREAD

**Issue by anh-duc-le** [Sitecore/Sitecore.Rocks#87] opened 2018-12-05 14:21 UTC
I would like to request a change for this warning message that occurs when you click too fast in the Sitecore Explorer. It really goes against your tagline of:

> Sitecore Rocks makes Sitecore developers happy!

It feels condescending to me as a user and can be slightly (read this as _very_) infuriating when you're already dealing with more important things on your head. 

![image](https://user-images.githubusercontent.com/37115195/49518526-250e9000-f89f-11e8-8785-6beba5ecac28.png)

This will be much appreciated.

**Comment by nickwesselman** [comment] 2019-01-22 13:55
Yuck, agreed, this message will not do. Can you provide more detail on how to reproduce the message? Maybe a screen capture? I have not seen it and some "quick" clicking around the item tree doesn't seem to repro for me.

**Comment by jaapdicker** [comment] 2019-01-22 14:11
![Here's a screen capture](https://thumbs.gfycat.com/PitifulPiercingHoopoe-small.gif)

**Comment by nickwesselman** [comment] 2019-01-22 14:13
I see, a quick 2X double-click can do it. Thanks!

**Comment by rroman81** [comment] 2019-03-01 06:58
@nickwesselman , any preferred convention for these types of messages that we want to adhere to?  I can take a look at the fix.

**Comment by nickwesselman** [comment] 2019-03-04 15:04
Hi @rroman81, that would be great! I haven't dug into the reasoning for this message yet, but if there's a better way to handle the scenario that doesn't require a message, that would be best case. Especially for a 2X double-click on the same item, seems like the 2nd could just be ignored, if there's a clean way to do it.

Otherwise something simple like, "Please wait, still loading your previous request."

Thanks!

**Comment by nickwesselman** [comment] 2019-07-19 15:55
Fixed in `develop`, will be in next Rocks release.

**Closed by nickwesselman** 2019-07-19 15:55 UTC
Labels: bug
