### ISSUE TITLE
Compatiblity with Visual Studio 2019

### ISSUE THREAD

**Issue by rroman81** [Sitecore/Sitecore.Rocks#88] opened 2018-12-13 23:36 UTC
I noticed that VS2019 marketplace does not have this extension.  Any plans around VS2019 support?

I have a version VS2019 preview on my developer VM, so for now my plan is to pull the code down and recompile with VS2019 sdk.  I'd love to help out, so any guidance what needs to be done to ensure that we have VS2019 support ironed out.

**Comment by nickwesselman** [comment] 2019-01-22 13:48
No explicit plans at this time for us to work on this. I would happily review a PR for VS2019 support.

**Comment by nickwesselman** [comment] 2019-01-22 17:35
I'm going to reopen this as it should be on the backlog either way. :)

**Comment by nickwesselman** [comment] 2019-04-10 16:41
It appears that in addition to updating metadata, we have some startup changes to make. Currently get some undesirable messaging on startup in VS19:
![image](https://user-images.githubusercontent.com/27013789/55897135-ec086400-5b8d-11e9-9df8-e6b6bbe4b623.png)

More info:
https://docs.microsoft.com/en-us/visualstudio/extensibility/synchronously-autoloaded-extensions?view=vs-2019
https://github.com/Microsoft/VSSDK-Extensibility-Samples/tree/master/AsyncPackageMigration

**Comment by rroman81** [comment] 2019-04-10 19:44
i have a branch that's kind of working but do concur that we need to rever to using the AsyncPackage class. That is still pending.

**Comment by nickwesselman** [comment] 2019-04-10 19:45
I'm in progress on it now, moving to `AsyncPackage` required a cascade of other changes but I think I'm on track.

**Comment by rroman81** [comment] 2019-04-13 02:13
@nickwesselman Looks like you took the updates a bit further than my branch. Do you want me to test the PR?

**Comment by nickwesselman** [comment] 2019-04-15 13:59
@rroman81 Feel free but my last test before I had to take off for the weekend included VS17 hard crashing.😆 ... latest PR build should always be available on AppVeyor though:
https://ci.appveyor.com/project/nickwesselman/sitecore-rocks

**Comment by nickwesselman** [comment] 2019-04-15 18:25
This build seems stable in VS17 and VS19, feel free to try it out:

https://ci.appveyor.com/api/buildjobs/6whd84ivthbstac6/artifacts/src%2FSitecore.Rocks.VisualStudio%2Fbin%2FRelease%2FSitecore.Rocks.VisualStudio.vsix

**Comment by nickwesselman** [comment] 2019-04-17 16:47
Latest build:
https://ci.appveyor.com/api/buildjobs/bv84wdonp8sgy641/artifacts/src%2FSitecore.Rocks.VisualStudio%2Fbin%2FRelease%2FSitecore.Rocks.VisualStudio.vsix

**Comment by nickwesselman** [comment] 2019-04-17 20:00
Latest build:

https://ci.appveyor.com/api/buildjobs/511j17my1v8tr148/artifacts/src%2FSitecore.Rocks.VisualStudio%2Fbin%2FRelease%2FSitecore.Rocks.VisualStudio.vsix

**Comment by scavezze** [comment] 2019-05-14 15:38
I gave the latest build a try but the Sitecore explorer won't open trying vs 2019 version 16.0.3

**Comment by nickwesselman** [comment] 2019-05-14 16:19
@scavezze You used the build in the link above? And when you select Sitecore Explorer from the Extensions menu, does anything happen at all?

**Comment by ppluijten** [comment] 2019-05-21 08:45
> Latest build:
> 
> https://ci.appveyor.com/api/buildjobs/511j17my1v8tr148/artifacts/src%2FSitecore.Rocks.VisualStudio%2Fbin%2FRelease%2FSitecore.Rocks.VisualStudio.vsix

This build works in my Visual Studio 2019 (16.0.3), thank you for the effort.

**Comment by nickwesselman** [comment] 2019-05-21 13:00
Latest build:
https://ci.appveyor.com/api/buildjobs/qs02fjft00ryde0k/artifacts/src%2FSitecore.Rocks.VisualStudio%2Fbin%2FRelease%2FSitecore.Rocks.VisualStudio.vsix

This includes resolution of the issue described in this KB:
https://kb.sitecore.net/articles/842902

**Comment by markgibbons25** [comment] 2019-05-23 23:31
> Latest build:
> https://ci.appveyor.com/api/buildjobs/qs02fjft00ryde0k/artifacts/src%2FSitecore.Rocks.VisualStudio%2Fbin%2FRelease%2FSitecore.Rocks.VisualStudio.vsix
> 
> This includes resolution of the issue described in this KB:
> https://kb.sitecore.net/articles/842902

Tested and working nicely on VS 16.1.0
Thanks Nick et al!

**Comment by lleopereira** [comment] 2019-05-24 14:41
I`m using the extension and find an issue while I`ve tried to create a template "Sitecore View Layout" or any other template. This issue has been fixed in other VS versions, just pasting the dll file "Sitecore.Rocks.TemplateWizard.dll" at "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\PublicAssemblies", but for me did not work. 

Do you guys are having the same issue?

**Comment by lizzyCoder** [comment] 2019-05-24 15:48
I am having the same issue as above, I also have the dll in the Public Assemblies folder and nothing. Had to resort back to VS2017.  :(

**Comment by lizzyCoder** [comment] 2019-05-24 15:49
@markgibbons25 Are your templates working?

**Comment by lleopereira** [comment] 2019-05-24 16:31
Same here. I'm going to use VS2017 for now then.

**Comment by markgibbons25** [comment] 2019-05-28 00:36
> @markgibbons25 Are your templates working?

Yes, I've no problem creating templates.

**Comment by lizzyCoder** [comment] 2019-05-28 12:39
> > @markgibbons25 Are your templates working?
> 
> Yes, I've no problem creating templates.

Can you confirm where your Sitecore.Rocks.TemplateWizard.dll lives? Just trying to find out what's different.  :/

**Comment by nickwesselman** [comment] 2019-06-03 17:43
@lizzyCoder @lleopereira I'm going to be completely honest -- I am not familiar with this feature of Rocks myself, and what it's supposed to do. The code itself is not very helpful. Perhaps @JakobChristensen can chime in or you would be willing to record a screenshare from VS17 showing the expected behavior?

**Comment by nickwesselman** [comment] 2019-06-03 19:40
Nevermind, I see now that this is just the connection of creating an item in SItecore when using the file templates included with Rocks. It does work for me, Rocks is finding the Template Wizard DLL in the GAC, so I did not need to install or place it anywhere. Will remove it and do some more testing.

**Comment by lizzyCoder** [comment] 2019-06-04 14:26
@nickwesselman  What is the GAC? So, you don't have the template in VS Public Assemblies folder??

**Comment by nickwesselman** [comment] 2019-06-04 19:38
Sorry for the commit spam on this issue, juggling both adding support for next version of Sitecore and support for VS19. Wanted to get this back on `master` where AppVeyor can successfully build.

@lizzyCoder @lleopereira @scavezze and all, please try this latest build:
https://ci.appveyor.com/api/buildjobs/p654icv8h1mrqlo2/artifacts/src%2FSitecore.Rocks.VisualStudio%2Fbin%2FRelease%2FSitecore.Rocks.VisualStudio.vsix

I believe I resolved the issue with the `TemplateWizard`. The VS templates are looking for a specific version of that assembly (`1.0.0.0`), which I still had in the GAC but that was no longer included in the VSIX, due to enabling of auto-versioning in AppVeyor. Long story short, this build should install the right version in the GAC, or allow you to place the correct version in `PublicAssemblies` if GAC install fails.

**Comment by lizzyCoder** [comment] 2019-06-06 19:08
Ok I am getting errors:
When I try to do a new connection under Extensions > Sitecore I get this
![image](https://user-images.githubusercontent.com/18193174/59059339-b2419a00-886c-11e9-8c08-49c7725e1960.png)

When I try to open the Sitecore Explorer I get this
![image](https://user-images.githubusercontent.com/18193174/59059398-def5b180-886c-11e9-9745-c82e05cac5fa.png)

**Comment by nickwesselman** [comment] 2019-06-07 16:41
@lizzyCoder Yikes, I am definitely not seeing that. Can you perhaps try uninstalling/reinstalling and if it's still erroring, provide the output of Help > About > Copy Info?

**Comment by lizzyCoder** [comment] 2019-06-07 17:11
Yup! Uninstalling and reinstalling worked. I'm connected now. Thank you for getting this to work!

**Comment by jnegron357** [comment] 2019-07-08 18:44
How do I install this for VS2019? I understand it's not released yet but I'd like to give it a test run. When I try the normal install with the VSIX I only get VS2017 option as a target.

**Comment by lizzyCoder** [comment] 2019-07-08 20:43
@jnegron357  I think VS2019 should be closed first, then try running the installer again.

**Comment by nickwesselman** [comment] 2019-07-19 15:56
Complete in `develop`, will be in next Rocks release.

**Closed by nickwesselman** 2019-07-19 15:56 UTC
Labels: enhancement

**Comment by jnegron357** [comment] 2019-08-29 13:23
This is working well with VS2019, thanks for the hard work guys! Much appreciated!

**Comment by awarberg** [comment] 2019-10-02 11:08
> Ok I am getting errors:
> When I try to do a new connection under Extensions > Sitecore I get this
> ![image](https://user-images.githubusercontent.com/18193174/59059339-b2419a00-886c-11e9-8c08-49c7725e1960.png)
> 
> When I try to open the Sitecore Explorer I get this
> ![image](https://user-images.githubusercontent.com/18193174/59059398-def5b180-886c-11e9-9745-c82e05cac5fa.png)
> 
> I did see that the new build does install the `TemplateWizard` in the` publicAssemblies` folder.

I am getting the same errors even after uninstalling and reinstalling (version 3.0.283). Do I need to uninstall/clean up Sitecore Rocks manually and how can I do that?

![image](https://user-images.githubusercontent.com/7944743/66039515-67334d00-e515-11e9-8664-4b766d0a1a12.png)

This is my About  / Copy Info:


```
Microsoft Visual Studio Professional 2019
Version 16.3.2
VisualStudio.16.Release/16.3.2+29326.143
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

Application Insights Tools for Visual Studio Package   9.1.00913.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.3.283.64955
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.3.283.64955
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.3.283.64955
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.3.283.64955
Azure Functions and Web Jobs Tools

C# Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeMaid   11.0.183
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper Ultimate 2019.1.3   Build 191.0.20190704.212735
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20816.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.83+gbc8a4b23ec
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   5.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Productivity Power Tools 2017/2019   16.0
Installs the individual extensions of Productivity Power Tools 2017/2019

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Sitecore.Rocks   1.0
Sitecore integration with Visual Studio 2010

SQL Server Data Tools   16.0.61908.27190
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10821.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19455.1+0422ff293bb2cc722fe5021b85ef50378a9af823
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
```

**Comment by nickwesselman** [comment] 2019-10-11 19:24
Hi @awarberg,

Thanks for reporting. I haven't seen reports of this issue before, I updated to the latest VS19, which now is 16.3.4, and cannot reproduce. Can you try updating to the latest VS19?

Also, I assume when you attempt to remove/reinstall, that you restart Visual Studio as required?

My only other thought is that another extension may be causing an issue. Can you try disabling your other extensions to see if the issue still reproduces?

Thanks!
-Nick

**Comment by awarberg** [comment] 2019-10-21 07:46
> Hi @awarberg,
> 
> Thanks for reporting. I haven't seen reports of this issue before, I updated to the latest VS19, which now is 16.3.4, and cannot reproduce. Can you try updating to the latest VS19?
> 
> Also, I assume when you attempt to remove/reinstall, that you restart Visual Studio as required?
> 
> My only other thought is that another extension may be causing an issue. Can you try disabling your other extensions to see if the issue still reproduces?
> 
> Thanks!
> -Nick

Thanks for the suggestions. I have tried installing Sitecore Rocks 3.0.283 on Visual Studio 16.3.4 but Sitecore Rocks still cannot launch. When I try to open New Connection, Sitecore Explorer, or event About, nothing happens (before the mentioned error message would appear, now nothing happens).

**Comment by nickwesselman** [comment] 2019-10-25 20:05
@awarberg Did you try disabling your other extensions?

**Comment by awarberg** [comment] 2019-10-28 07:58
> @awarberg Did you try disabling your other extensions?

I have tried disabling my extensions (except for ReSharper, which I could not do without). I am no longer getting the silent treatment but instead a bunch of error messages. I have attached the ActivityLog, maybe you can get something meaningful out of it.

[ActivityLog.txt](https://github.com/Sitecore/Sitecore.Rocks/files/3777655/ActivityLog.txt)

**Comment by babyhello** [comment] 2019-10-29 03:39
VS 2019 Create SiteCore View Rendering Show Error

![image](https://user-images.githubusercontent.com/9627599/67735896-848a0700-fa40-11e9-8d48-fc01f12e4a80.png)

![image](https://user-images.githubusercontent.com/9627599/67735920-9370b980-fa40-11e9-9303-4dacb15cdca7.png)

I can't create any about SiteCore items
